language: node_js
node_js: "12"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - js
    - css
# services:
#   - mysql
install:
  - npm install
script:
  - npm run production