language: node_js
node_js: "12"
branches:
  only:
    - main
    - staging
cache:
  directories:
    - node_modules
# services:
#   - mysql
before_install:
  - npm i --only=dev
  - npm run test
# install:
#   - npm install
# script:
#   - npm run production