export const REGISTER_MODAL = "REGISTER_MODAL";
export const SET_ACTIVE_MODAL = "SET_ACTIVE_MODAL";
export const SET_ACTIVE_ROOM = "SET_ACTIVE_ROOM";
export const DEREGISTER_MODAL = "DEREGISTER_MODAL";


