module.exports = {
    /**
     * ROOM PERMISSIONS
     */
    VIEW_ROOM: "VIEW_ROOM",
    UPDATE_ROOM: "UPDATE_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    ARCHIVE_ROOM: "ARCHIVE_ROOM",

    /**
     * STUDENT PERMISSIONS
     */
    CREATE_STUDENT: "CREATE_STUDENT",
    VIEW_STUDENT: "VIEW_STUDENT",
    UPDATE_STUDENT: "UPDATE_STUDENT",
    DELETE_STUDENT: "DELETE_STUDENT"
}