#  Name of workflow
name: Test workflow
# Trigger workflow on all pull requests
on:
    pull_request:
        branches:
            - staging
            - main
# Jobs to carry out
jobs:
    test:
        # Operating system to run job on
        runs-on: ubuntu-latest
        # Steps in job
        steps:
            # Get code from repo
            - name: Checkout code
              uses: actions/checkout@v1
            # Install NodeJS
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            # Build the app
            - name: 🧰 install dev deps
              run: npm i --only=dev
            - name: Run test
              run: npm run test