/**
 * TOPBAR ACTIONS
 */
export const SET_TOPBAR = "SET_TOPBAR";

/**
 * STUDENT VIEW ACTIONS
 */
export const SET_STUDENTS = "SET_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const UPDATE_STUDENT = "ADD_STUDENT";
export const REMOVE_STUDENT = "REMOVE_STUDENT";